name: heart-disease-algorithm
channels:
  - conda-forge
  - default
dependencies:
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - jupyter
  - python
  - numpy
  - ipywidgets
  - seaborn
  - voila